### ISSUE TITLE
第三个 弹出框，方法名称和html中的方法名称为什么不一样呢

### ISSUE THREAD

**Issue by qluojieq** [YanlongMa/SwiftJavaScriptCore#1]
，还有传递多个参数的情况怎么办呢，第一个，当我修改为传递两个参数时就不执行了，

**Comment by yanlongma** [comment]
多个参数时，将swift第二个及以后的参数提到方法名中。 如Swift函数为func(param1: String, param2: String, param3: String)， js调用时为funcParam2Param3。
